stages:
  - lint
  - test

variables:
  GOPROXY: "https://proxy.golang.org"

lint:
  stage: lint
  image: golang:1.22
  script:
    - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    - golangci-lint run
  only:
    - main
    - merge_requests

test:
  stage: test
  image: golang:1.20
  script:
    - go test ./... -v -race -coverprofile=coverage.out
    - go tool cover -func=coverage.out
  artifacts:
    reports:
      junit: junit.xml
    paths:
      - coverage.out
  only:
    - main
    - merge_requests
