version: "3.9"

services:
  app:
    build:
      context: admin
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ADMIN_POSTGRES_URL: "postgres://postgres:password@db:5432/ctfplatform?sslmode=disable"
      ADMIN_REDIS_URL: "redis://cache:6379"
      ADMIN_APP_PORT: "8080"
    depends_on:
      - db
      - cache

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ctfplatform
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  cache:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  postgres-data:
  redis-data: